//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public long IdFactura { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Total { get; set; }
        public decimal Precio { get; set; }
        public long IdSuscripcion { get; set; }
    
        public virtual Suscripcion Suscripcion { get; set; }
        public virtual Suscripcion Suscripcion1 { get; set; }
    }
}
