//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class InscritoEn
    {
        public long IdInscritoEn { get; set; }
        public long IdClase { get; set; }
        public long IdUsuario { get; set; }
    
        public virtual Clase Clase { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
