//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class InscritoEn
    {
        public long IdInscritoEn { get; set; }
        public long IdClase { get; set; }
        public long IdUsuario { get; set; }
    
        public virtual Clase Clase { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
